version: '3.1'

services:

  studysafe:
    build:
      context: ./studysafe
      args:
        PORT: 8000
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'false'
      SECRET_KEY: 'OmX4cmApze0ZxtkhSnKHBPk4bQNOFRDqswYlcDMu'
      DATABASE_URL: 'postgres://postgres:very-secure-password@db:5432/studysafe'
      PORT: 8000

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: very-secure-password
      POSTGRES_DB: studysafe
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
