# Generated by Django 4.0.4 on 2022-04-18 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('studysafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitingrecord',
            options={'permissions': [('can_enter_venue', 'Can enter venue'),
                                     ('can_exit_venue', 'Can exit venue')]},
        ),
    ]
